// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Message(props) {
  return JsxRuntime.jsx("p", {
    children: props.msg,
    className: "text-stone-100 absolute -top-20 w-4/5 bg-red-800 p-2 left-1/2 transform -translate-x-2/4 text-center font-anon text-sm"
  });
}

let make = Message;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
