// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function queryToString(q) {
  switch (q) {
    case "VerificationCode" :
      return "cd_un";
    case "ForgotPassword" :
      return "pw_un";
    case "ForgotUsername" :
      return "un_em";
    case "Other" :
      return "";
  }
}

function authSubrouteToString(a) {
  if (typeof a === "object") {
    return `play/` + a.play;
  }
  switch (a) {
    case "Leaderboard" :
      return "leaderboard";
    case "Lobby" :
      return "lobby";
    case "Other" :
      return "";
  }
}

function typeToUrlString(t) {
  if (typeof t !== "object") {
    switch (t) {
      case "Home" :
        return "/";
      case "SignIn" :
        return "/signin";
      case "SignUp" :
        return "/signup";
      case "Other" :
        return "";
    }
  } else {
    switch (t.TAG) {
      case "GetInfo" :
        return `/getinfo?` + queryToString(t.search);
      case "Confirm" :
        return `/confirm?` + queryToString(t.search);
      case "Auth" :
        return `/auth/` + authSubrouteToString(t.subroute);
    }
  }
}

function useRouter() {
  let url = RescriptReactRouter.useUrl(undefined, undefined);
  let match = url.path;
  if (match === 0) {
    return "Home";
  }
  switch (match.hd) {
    case "auth" :
      let l = match.tl;
      if (l === 0) {
        return {
          TAG: "Auth",
          subroute: "Other"
        };
      }
      switch (l.hd) {
        case "leaderboard" :
          if (l.tl !== 0) {
            return {
              TAG: "Auth",
              subroute: "Other"
            };
          } else {
            return {
              TAG: "Auth",
              subroute: "Leaderboard"
            };
          }
        case "lobby" :
          if (l.tl !== 0) {
            return {
              TAG: "Auth",
              subroute: "Other"
            };
          } else {
            return {
              TAG: "Auth",
              subroute: "Lobby"
            };
          }
        case "play" :
          let match$1 = l.tl;
          if (match$1 !== 0 && match$1.tl === 0) {
            return {
              TAG: "Auth",
              subroute: {
                TAG: "Play",
                play: match$1.hd
              }
            };
          } else {
            return {
              TAG: "Auth",
              subroute: "Other"
            };
          }
        default:
          return {
            TAG: "Auth",
            subroute: "Other"
          };
      }
    case "confirm" :
      if (match.tl !== 0) {
        return "Other";
      } else {
        let s = url.search;
        switch (s) {
          case "cd_un" :
            return {
              TAG: "Confirm",
              search: "VerificationCode"
            };
          case "pw_un" :
            return {
              TAG: "Confirm",
              search: "ForgotPassword"
            };
          default:
            return "Other";
        }
      }
    case "getinfo" :
      if (match.tl !== 0) {
        return "Other";
      } else {
        let s$1 = url.search;
        switch (s$1) {
          case "cd_un" :
            return {
              TAG: "GetInfo",
              search: "VerificationCode"
            };
          case "pw_un" :
            return {
              TAG: "GetInfo",
              search: "ForgotPassword"
            };
          case "un_em" :
            return {
              TAG: "GetInfo",
              search: "ForgotUsername"
            };
          default:
            return "Other";
        }
      }
    case "signin" :
      if (match.tl !== 0) {
        return "Other";
      } else {
        return "SignIn";
      }
    case "signup" :
      if (match.tl !== 0) {
        return "Other";
      } else {
        return "SignUp";
      }
    default:
      return "Other";
  }
}

function replace(route) {
  RescriptReactRouter.replace(typeToUrlString(route));
}

function push(route) {
  RescriptReactRouter.push(typeToUrlString(route));
}

export {
  typeToUrlString,
  useRouter,
  replace,
  push,
}
/* RescriptReactRouter Not a pure module */
